### ISSUE TITLE
Cantonese support

### ISSUE THREAD

**Issue by chickendude** [JorisKok/chinese-firefox-quantum#2]
Any plans on improving the Cantonese support? The tone system used is a bit odd, it might be easier just to use the tone numbers themselves. Also, what dictionary are you using? A lot of words are missing, at first i thought only individual characters were supported, but i just tried searching some of the multi-character words in the dictionary and they do show up. I thought CantoDict was available under a free license but apparently it's not, which is really a shame.

Thanks for all your work getting this up and running, if you have a PayPal account or some other way to send donations, please make it available somewhere!

**Comment by Kottakji** [comment]
I want to, but I was a bit busy these days. Also, could you point me in the right direction as to what dictionary I should use or what kind of tone system?
I've used http://www.cantonese.sheik.co.uk/scripts/masterlist.htm?level=1 this one, with the jyutping system. That is CantoDict isn't it? I just put a script to run over the master list and saved it locally. Also, the pinyin from there is what you want to use? Or is there a seperate system?

**Comment by chickendude** [comment]
The tones in the dictionary are correct, but the tone markers are weird. For example, it's showing me the Mandarin 3rd tone for some words, which i've never seen used before other than some manuals for Chinese students which just lump the Cantonese tones into the Mandarin system. The system that is the easiest to follow is like this:
我飲咖啡，但係我唔飲茶 。
ngő jám gaafē, da̱anha̱i ngő m̏ jám cȁa.

**Tones in regular numbers:**
fē = fe1
jám = jam2
gaa = gaa3
m̏ = m4
ngő = ngo5
da̱anha̱i = daan6hai6

A double accent means that it's a low tone, a single accent is a high tone, no accent means it's a mid-tone, and the line on the bottom means it's a low tone.

And yeah, that is CantoDict, but that section appears to only have individual characters, not words. I think this is the list of words:  
http://www.cantonese.sheik.co.uk/dictionary/words/
(or divided into levels)
http://www.cantonese.sheik.co.uk/scripts/wordlist.htm?level=1

**Comment by Kottakji** [comment]
Ah I see! Will try to fix that asap. Then hopefully I will get the additional words imported later! Thanks

**Comment by Kottakji** [comment]
Tones can only be placed on a, e, i, u, v and m right? The m is a special case in Cantonese?

**Comment by Kottakji** [comment]
I've updated the extension with a fix for the tones. The color coding doesn't work yet in Cantonese, but I will do that later.
