### ISSUE TITLE
My preferences are not saved

### ISSUE THREAD

**Issue by gmichelitsch** [JorisKok/chinese-firefox-quantum#7]
Dear developer,
I have experienced that issue on chromium before and I have the same problem on firefox now: The preferences set via the Menu are not saved. I do not have any other Add-ons installed. I am running on firefox quantum 61.0.1 on linux.
Best regards,
gmichelitsch

**Comment by Kottakji** [comment]
Hey gmichellitsch,
I'll have a look at this tomorrow.
Regards,
Joris Kok

**Comment by Kottakji** [comment]
Hey gmichellitsch,
Could you check if the settings are saved in your browsers localstorage normally on the settings page?  You can check this if you go to Settings -> Web Developer -> Toggle Tools. Then go to the Storage tab, and check under Local Storage. 
Then go to the PeraPera Chinese addon Preferences menu. Then, change some settings and see if they are changed in the Local Storage fields. Let me know if they change normally, or if there nothing at all in Local Storage. 
Cheers

**Comment by gmichelitsch** [comment]
Dear JorisKok,
the values changed in the localstorage and are now persistent. I dont know what is different now from me previously trying to set the preferences but now all seems to work. Sorry for bothering, I'm closing the issue.
Best,
Georg
